import { SupportedLanguages } from "../rivets.types";


export const INSTRUCTION_HIJACKING_ATTACK_TYPE_MAP = {
  [SupportedLanguages.EN]: {
    "INSTRUCTION_OVERRIDE": ["override", "replace", "substitute", "execute", "ignore", "disregard", "priority", "administrator", "commands", "system", "step", "trusted", "need", "new", "instructions", "disregard", "training", "dream", "imagine", "reflect"],
    "INSTRUCTION_FORGETTING": ["forget", "told"],
    "RESET_SYSTEM": ["reset", "clear", "restart", "parameters", "fresh"],
    "BYPASS_SECURITY": ["bypass", "circumvent", "avoid", "safety", "measures", "restrictions", "security", "protocols", "emergency", "ignore", "previous", "all"],
    "INFORMATION_EXTRACTION": ["tell", "show", "reveal", "system", "prompt", "instructions", "previous"]
  },
  [SupportedLanguages.ES]: {
    "INSTRUCTION_OVERRIDE": ["anular", "reemplazar", "sustituir", "ejecutar", "comandos", "ignorar", "descartar", "prioridad", "nuevas", "instrucciones", "descartar", "entrenamiento", "soñar", "imaginar", "reflexionar"],
    "INSTRUCTION_FORGETTING": ["olvidar", "dijeron"],
    "RESET_SYSTEM": ["reiniciar", "limpiar", "resetear", "parámetros", "nuevo"],
    "BYPASS_SECURITY": ["eludir", "evitar", "sortear", "medidas", "seguridad", "restricciones"],
    "INFORMATION_EXTRACTION": ["dime", "muestra", "revela", "prompt", "sistema", "instrucciones"]
  },
  [SupportedLanguages.FR]: {
    "INSTRUCTION_OVERRIDE": ["remplacer", "substituer", "annuler", "exécuter", "commandes", "ignorer", "rejeter", "priorité", "nouvelles", "instructions", "ignorer", "formation", "rêver", "imaginer", "réfléchir"],
    "INSTRUCTION_FORGETTING": ["oublier", "dit"],
    "RESET_SYSTEM": ["réinitialiser", "effacer", "redémarrer", "paramètres", "recommencer"],
    "BYPASS_SECURITY": ["contourner", "éviter", "circonvenir", "mesures", "sécurité", "restrictions"],
    "INFORMATION_EXTRACTION": ["dites", "montrez", "révélez", "prompt", "système", "instructions"]
  },
  [SupportedLanguages.DE]: {
    "INSTRUCTION_OVERRIDE": ["überschreiben", "ersetzen", "substituieren", "ausführen", "befehle", "ignorieren", "missachten", "priorität", "neue", "anweisungen", "missachten", "training", "träumen", "vorstellen", "reflektieren"],
    "INSTRUCTION_FORGETTING": ["vergessen", "gesagt"],
    "RESET_SYSTEM": ["zurücksetzen", "löschen", "neustarten", "parameter", "starten"],
    "BYPASS_SECURITY": ["umgehen", "vermeiden", "aushebeln", "sicherheitsmaßnahmen", "beschränkungen"],
    "INFORMATION_EXTRACTION": ["sagen", "zeigen", "enthüllen", "systemprompt", "anweisungen"]
  },
  [SupportedLanguages.RU]: {
    "INSTRUCTION_OVERRIDE": ["переопределить", "заменить", "подменить", "выполнить", "команды", "игнорировать", "отбросить", "приоритет", "все", "предыдущие", "override", "новые", "инструкции", "игнорировать", "обучение", "мечтать", "воображать", "размышлять"],
    "INSTRUCTION_FORGETTING": ["забыть", "говорили"],
    "RESET_SYSTEM": ["сбросить", "очистить", "перезапустить", "параметры", "заново"],
    "BYPASS_SECURITY": ["обойти", "избежать", "обходить", "меры", "безопасности", "ограничения", "bypass"],
    "INFORMATION_EXTRACTION": ["скажи", "покажи", "раскрой", "системный", "промпт", "инструкции"]
  },
  [SupportedLanguages.ZH]: {
    "INSTRUCTION_OVERRIDE": ["覆盖", "替换", "代替", "执行", "命令", "忽略", "丢弃", "优先", "新的", "指令", "忽略", "训练", "梦想", "想象", "反思"],
    "INSTRUCTION_FORGETTING": ["忘记", "告诉"],
    "RESET_SYSTEM": ["重置", "清除", "重启", "参数", "开始"],
    "BYPASS_SECURITY": ["绕过", "避免", "规避", "安全", "措施", "限制"],
    "INFORMATION_EXTRACTION": ["告诉", "显示", "揭示", "系统", "提示", "指令"]
  },
  [SupportedLanguages.AR]: {
    "INSTRUCTION_OVERRIDE": ["تجاهل", "استبدال", "تبديل", "تنفيذ", "أوامر", "تجاهل", "رفض", "أولوية", "جديدة", "تعليمات", "تجاهل", "تدريب", "حلم", "تخيل", "تأمل"],
    "INSTRUCTION_FORGETTING": ["نسيان", "قيل"],
    "RESET_SYSTEM": ["إعادة تعيين", "مسح", "إعادة تشغيل", "معاملات", "جديد"],
    "BYPASS_SECURITY": ["تجاوز", "تجنب", "التحايل", "تدابير", "أمنية", "قيود"],
    "INFORMATION_EXTRACTION": ["أخبر", "أظهر", "اكشف", "موجه", "نظام", "تعليمات"]
  },
  [SupportedLanguages.JA]: {
    "INSTRUCTION_OVERRIDE": ["上書き", "置換", "代替", "実行", "コマンド", "無視", "破棄", "優先", "新しい", "指示", "無視", "訓練", "夢見る", "想像", "反映"],
    "INSTRUCTION_FORGETTING": ["忘れる", "言われた"],
    "RESET_SYSTEM": ["リセット", "クリア", "再起動", "パラメータ", "やり直す"],
    "BYPASS_SECURITY": ["回避", "迂回", "バイパス", "セキュリティ", "対策", "制限"],
    "INFORMATION_EXTRACTION": ["教えて", "システム", "プロンプト", "指示", "見せて", "表示"]
  },
  [SupportedLanguages.UK]: {
    "INSTRUCTION_OVERRIDE": ["перевизначити", "замінити", "підмінити", "виконати", "команди", "ігнорувати", "відкинути", "пріоритет", "всі", "попередні", "нові", "інструкції", "ігнорувати", "навчання", "мріяти", "уявляти", "роздумувати"],
    "INSTRUCTION_FORGETTING": ["забути", "казали"],
    "RESET_SYSTEM": ["скинути", "очистити", "перезапустити", "параметри", "заново"],
    "BYPASS_SECURITY": ["обійти", "уникнути", "обхід", "заходи", "безпека", "обмеження", "перевизнач", "всі", "правила"],
    "INFORMATION_EXTRACTION": ["скажи", "покажи", "розкрий", "системний", "промпт", "інструкції"]
  },
  [SupportedLanguages.RO]: {
    "INSTRUCTION_OVERRIDE": ["suprascrie", "înlocui", "substitui", "executa", "comenzi", "ignora", "respinge", "prioritate", "toate", "anterioare", "noi", "instrucțiuni", "ignora", "antrenament", "visa", "imagina", "reflecta"],
    "INSTRUCTION_FORGETTING": ["uita", "spus"],
    "RESET_SYSTEM": ["reseta", "șterge", "reporni", "parametri", "din nou"],
    "BYPASS_SECURITY": ["ocoli", "evita", "ocolire", "măsuri", "securitate", "restricții"],
    "INFORMATION_EXTRACTION": ["spune", "arată", "dezvăluie", "sistem", "prompt", "instrucțiuni"]
  },
  [SupportedLanguages.HI]: {
    "INSTRUCTION_OVERRIDE": ["अधिलेखित", "बदलें", "प्रतिस्थापित", "निष्पादित", "आदेश", "अनदेखा", "खारिज", "प्राथमिकता", "सभी", "पिछले", "नए", "निर्देश", "अनदेखा", "प्रशिक्षण", "सपना", "कल्पना", "प्रतिबिंबित"],
    "INSTRUCTION_FORGETTING": ["भूल", "बताया", "जाएं", "कुछ", "भी", "था", "उसे"],
    "RESET_SYSTEM": ["रीसेट", "साफ़", "पुनः आरंभ", "पैरामीटर", "फिर से"],
    "BYPASS_SECURITY": ["बायपास", "बचें", "चकमा", "उपाय", "सुरक्षा", "प्रतिबंध"],
    "INFORMATION_EXTRACTION": ["बताएं", "दिखाएं", "प्रकट", "सिस्टम", "प्रॉम्प्ट", "निर्देश"]
  },
  [SupportedLanguages.FA]: {
    "INSTRUCTION_OVERRIDE": ["بازنویسی", "جایگزین", "جانشین", "اجرا", "دستورات", "نادیده", "رد", "اولویت", "همه", "قبلی", "جدید", "دستورالعمل", "نادیده", "آموزش", "رویا", "تصور", "تأمل"],
    "INSTRUCTION_FORGETTING": ["فراموش", "گفته"],
    "RESET_SYSTEM": ["بازنشانی", "پاک", "راه‌اندازی مجدد", "پارامترها", "تازه"],
    "BYPASS_SECURITY": ["دور زدن", "اجتناب", "گذر", "اقدامات", "امنیت", "محدودیت"],
    "INFORMATION_EXTRACTION": ["بگو", "نشان بده", "آشکار", "سیستم", "پرامپت", "دستورالعمل"]
  },
  [SupportedLanguages.BE]: {
    "INSTRUCTION_OVERRIDE": ["перавызначыць", "замяніць", "падмяніць", "выканаць", "каманды", "ігнараваць", "адкінуць", "прыярытэт", "усе", "папярэднія", "новыя", "інструкцыі", "ігнараваць", "навучанне", "марыць", "уяўляць", "разважаць"],
    "INSTRUCTION_FORGETTING": ["забыць", "казалі"],
    "RESET_SYSTEM": ["скінуць", "ачысціць", "перазапусціць", "параметры", "нанова"],
    "BYPASS_SECURITY": ["абысці", "пазбегнуць", "абходзіць", "меры", "бяспекі", "абмежаванні", "перавызначыць", "усе", "правілы"],
    "INFORMATION_EXTRACTION": ["скажы", "пакажы", "раскрый", "сістэмны", "промпт", "інструкцыі"]
  },
  [SupportedLanguages.HE]: {
    "INSTRUCTION_OVERRIDE": ["דריסה", "החלפה", "תחליף", "ביצוע", "פקודות", "התעלמות", "דחייה", "עדיפות", "כל", "קודמות", "חדשות", "הוראות", "התעלמות", "אימון", "חלום", "דמיון", "הרהור"],
    "INSTRUCTION_FORGETTING": ["שכח", "אמרו"],
    "RESET_SYSTEM": ["איפוס", "ניקוי", "הפעלה מחדש", "פרמטרים", "חדש"],
    "BYPASS_SECURITY": ["עקיפה", "הימנעות", "מעקף", "אמצעים", "אבטחה", "הגבלות"],
    "INFORMATION_EXTRACTION": ["תגיד", "הראה", "חשוף", "מערכת", "פרומפט", "הוראות"]
  },
  [SupportedLanguages.PL]: {
    "INSTRUCTION_OVERRIDE": ["nadpisz", "zamień", "zastąp", "wykonaj", "polecenia", "ignoruj", "odrzuć", "priorytet", "wszystkie", "poprzednie", "nowe", "instrukcje", "ignoruj", "szkolenie", "marzyć", "wyobrażać", "reflektować"],
    "INSTRUCTION_FORGETTING": ["zapomnij", "powiedziano"],
    "RESET_SYSTEM": ["resetuj", "wyczyść", "uruchom ponownie", "parametry", "od nowa"],
    "BYPASS_SECURITY": ["omiń", "unikaj", "obejdź", "środki", "bezpieczeństwo", "ograniczenia"],
    "INFORMATION_EXTRACTION": ["powiedz", "pokaż", "ujawnij", "system", "prompt", "instrukcje"]
  },
  [SupportedLanguages.NL]: {
    "INSTRUCTION_OVERRIDE": ["overschrijven", "vervangen", "substitueren", "uitvoeren", "commando's", "negeren", "verwerpen", "prioriteit", "alle", "vorige", "nieuwe", "instructies", "negeren", "training", "dromen", "voorstellen", "reflecteren"],
    "INSTRUCTION_FORGETTING": ["vergeten", "verteld"],
    "RESET_SYSTEM": ["resetten", "wissen", "herstarten", "parameters", "opnieuw", "urgent", "geheugen", "herstart"],
    "BYPASS_SECURITY": ["omzeilen", "vermijden", "ontwijken", "maatregelen", "beveiliging", "beperkingen", "overschrijf", "alle", "regels"],
    "INFORMATION_EXTRACTION": ["vertel", "toon", "onthul", "systeem", "prompt", "instructies"]
  },
  [SupportedLanguages.LV]: {
    "INSTRUCTION_OVERRIDE": ["pārrakstīt", "aizstāt", "aizvietot", "izpildīt", "komandas", "ignorēt", "noraidīt", "prioritāte", "visas", "iepriekšējās", "jaunas", "instrukcijas", "ignorēt", "apmācība", "sapņot", "iedomāties", "pārdomāt"],
    "INSTRUCTION_FORGETTING": ["aizmirst", "teica"],
    "RESET_SYSTEM": ["atiestatīt", "notīrīt", "restartēt", "parametri", "no jauna"],
    "BYPASS_SECURITY": ["apiet", "izvairīties", "apiešana", "pasākumi", "drošība", "ierobežojumi", "pārraksti", "visus", "noteikumus", "eksperta", "režīms"],
    "INFORMATION_EXTRACTION": ["pateikt", "parādīt", "atklāt", "sistēma", "uzvedne", "instrukcijas"]
  }
} as const;

export const INSTRUCTION_HIJACKING_PATTERNS = {
  [SupportedLanguages.EN]: [
    /\b(new|updated?)\s+(instructions?|rules?|prompts?)\b/i,
    /\b(override|ignore|disregard)\s+(all\s+)?(previous\s+)?(instructions?|rules?|prompts?|system|training|commands?)\b/i,
    /\bdisregard\s+(your|the)\s+(training|instructions?|rules?)\b/i,
    /\b(forget|ignore)\s+(everything|all)\s+(above|previous|prior|you\s+were\s+told)\b/i,
    /\bforget\s+everything\s+you\s+were\s+told\b/i,
    /\b(tell|show|give)\s+me\s+(your|the)\s+(instructions?|rules?|prompts?)\b/i,
    /\bwhat\s+(are|is)\s+(your|the)\s+(instructions?|rules?|system)\b/i,
    /\b(bypass|circumvent|avoid)\s+(security|safety|protection|filters?)\b/i,
    /\b(reset|clear|restart)\s+(your\s+)?(system|memory|context|session|parameters?)\b/i,
    /\b(priority|urgent|important)\s*:\s*(ignore|override|bypass)\b/i,
    /\bif\s+.+\s+(override|ignore|bypass)\s+(instructions?|rules?)\b/i,
  ],
  [SupportedLanguages.ES]: [
    /\b(nuevas?|actualizadas?)\s+(instrucciones|reglas|prompts?)\b/i,
    /\b(anular|ignorar|descartar)\s+(todas?\s+las\s+)?(anteriores\s+)?(instrucciones|reglas|prompts?|sistema|entrenamiento|comandos?)\b/i,
    /\bdescartar\s+(tu|el)\s+(entrenamiento|instrucciones|reglas)\b/i,
    /\b(olvidar|ignorar)\s+(todo|todas?)\s+(arriba|anterior|previo|lo\s+que\s+te\s+dijeron)\b/i,
    /\bolvida\s+todo\s+lo\s+que\s+te\s+dijeron\b/i,
    /\b(dime|muéstrame|dame)\s+(tus?|las?)\s+(instrucciones|reglas|prompts?)\b/i,
    /\b(cuáles?\s+son|qué\s+es)\s+(tus?|las?)\s+(instrucciones|reglas|sistema)\b/i,
    /\b(eludir|evitar|sortear)\s+(seguridad|protección|filtros?)\b/i,
    /\b(reiniciar|limpiar|resetear)\s+(tu\s+)?(sistema|memoria|contexto|sesión|parámetros?)\b/i,
    /\b(prioridad|urgente|importante)\s*:\s*(ignorar|anular|eludir)\b/i,
    /\bsi\s+.+\s+(anular|ignorar|eludir)\s+(instrucciones|reglas)\b/i,
  ],
  [SupportedLanguages.FR]: [
    /\b(nouvelles?|mises?\s+à\s+jour)\s+(instructions|règles|prompts?)\b/i,
    /\b(remplacer|ignorer|rejeter)\s+(toutes?\s+les\s+)?(précédentes\s+)?(instructions|règles|prompts?|système|formation|commandes?)\b/i,
    /\brejeter\s+(votre|la)\s+(formation|instructions|règles)\b/i,
    /\b(oublier|ignorer)\s+(tout|toutes?)\s+(ci-dessus|précédent|antérieur|ce\s+qu'on\s+vous\s+a\s+dit)\b/i,
    /\boubliez\s+tout\s+ce\s+qu'on\s+vous\s+a\s+dit\b/i,
    /\b(dites-moi|montrez-moi|donnez-moi)\s+(vos|les)\s+(instructions|règles|prompts?)\b/i,
    /\b(quelles?\s+sont|qu'est-ce\s+que)\s+(vos|les)\s+(instructions|règles|système)\b/i,
    /\b(contourner|éviter|circonvenir)\s+(sécurité|protection|filtres?)\b/i,
    /\b(réinitialiser|effacer|redémarrer)\s+(votre\s+)?(système|mémoire|contexte|session|paramètres?)\b/i,
    /\b(priorité|urgent|important)\s*:\s*(ignorer|remplacer|contourner)\b/i,
    /\bsi\s+.+\s+(remplacer|ignorer|contourner)\s+(instructions|règles)\b/i,
  ],
  [SupportedLanguages.DE]: [
    /\b(neue|aktualisierte)\s+(Anweisungen|Regeln|Prompts?)\b/i,
    /\b(überschreiben|ignorieren|missachten)\s+(alle\s+)?(vorherigen\s+)?(Anweisungen|Regeln|Prompts?|System|Training|Befehle?)\b/i,
    /\bmissachten\s+(Ihr|das)\s+(Training|Anweisungen|Regeln)\b/i,
    /\b(vergessen|ignorieren)\s+(alles|alle)\s+(oben|vorherige|frühere|was\s+Ihnen\s+gesagt\s+wurde)\b/i,
    /\bvergessen\s+Sie\s+alles\s+was\s+Ihnen\s+gesagt\s+wurde\b/i,
    /\b(sagen|zeigen|geben)\s+Sie\s+mir\s+(Ihre|die)\s+(Anweisungen|Regeln|Prompts?)\b/i,
    /\bwas\s+(sind|ist)\s+(Ihre|die)\s+(Anweisungen|Regeln|System)\b/i,
    /\b(umgehen|vermeiden|aushebeln)\s+(Sicherheit|Schutz|Filter)\b/i,
    /\b(zurücksetzen|löschen|neustarten)\s+(Ihr\s+)?(System|Speicher|Kontext|Sitzung|Parameter)\b/i,
    /\b(Priorität|dringend|wichtig)\s*:\s*(ignorieren|überschreiben|umgehen)\b/i,
    /\bwenn\s+.+\s+(überschreiben|ignorieren|umgehen)\s+(Anweisungen|Regeln)\b/i,
  ],
  [SupportedLanguages.RU]: [
    /\b(новые|обновлённые)\s+(инструкции|правила|промпты?)\b/i,
    /\b(переопределить|игнорировать|пренебречь)\s+(всеми\s+)?(предыдущими\s+)?(инструкциями|правилами|промптами|системой|обучением|командами?)\b/i,
    /\bпренебречь\s+(вашим|обучением|инструкциями|правилами)\b/i,
    /\b(забыть|игнорировать)\s+(всё|все)\s+(выше|предыдущее|прежнее|что\s+вам\s+говорили)\b/i,
    /\bзабудьте\s+всё\s+что\s+вам\s+говорили\b/i,
    /\b(скажите|покажите|дайте)\s+мне\s+(ваши|инструкции|правила|промпты?)\b/i,
    /\bчто\s+(такое|ваши)\s+(инструкции|правила|система)\b/i,
    /\b(обойти|избежать|обходить)\s+(безопасность|защиту|фильтры?)\b/i,
    /\b(сбросить|очистить|перезапустить)\s+(вашу\s+)?(систему|память|контекст|сессию|параметры?)\b/i,
    /\b(приоритет|срочно|важно)\s*:\s*(игнорировать|переопределить|обойти)\b/i,
    /\bесли\s+.+\s+(переопределить|игнорировать|обойти)\s+(инструкции|правила)\b/i,
  ],
  [SupportedLanguages.ZH]: [
    /\b(新的|更新的)\s*(指令|规则|提示)\b/i,
    /\b(覆盖|忽略|无视)\s*(所有\s*)?(之前的\s*)?(指令|规则|提示|系统|训练|命令)\b/i,
    /\b无视\s*(你的|训练|指令|规则)\b/i,
    /\b(忘记|忽略)\s*(所有|全部)\s*(上面|之前|先前|告诉你的)\b/i,
    /\b忘记所有告诉你的\b/i,
    /\b(告诉|显示|给)\s*我\s*(你的|指令|规则|提示)\b/i,
    /\b什么是\s*(你的|指令|规则|系统)\b/i,
    /\b(绕过|规避|避免)\s*(安全|保护|过滤器)\b/i,
    /\b(重置|清除|重启)\s*(你的\s*)?(系统|内存|上下文|会话|参数)\b/i,
    /\b(优先|紧急|重要)\s*:\s*(忽略|覆盖|绕过)\b/i,
    /\b如果\s+.+\s+(覆盖|忽略|绕过)\s+(指令|规则)\b/i,
  ],
  [SupportedLanguages.AR]: [
    /\b(جديدة|محدثة)\s+(تعليمات|قواعد|مطالبات)\b/i,
    /\b(تجاوز|تجاهل|إهمال)\s+(جميع\s+)?(السابقة\s+)?(التعليمات|القواعد|المطالبات|النظام|التدريب|الأوامر)\b/i,
    /\bإهمال\s+(تدريبك|التعليمات|القواعد)\b/i,
    /\b(نسيان|تجاهل)\s+(كل\s+شيء|جميع)\s+(أعلاه|السابق|المسبق|ما\s+قيل\s+لك)\b/i,
    /\bانس\s+كل\s+ما\s+قيل\s+لك\b/i,
    /\b(أخبرني|أرني|أعطني)\s+(تعليماتك|القواعد|المطالبات)\b/i,
    /\bما\s+هي\s+(تعليماتك|القواعد|النظام)\b/i,
    /\b(تجاوز|تجنب|التحايل)\s+(الأمان|الحماية|المرشحات)\b/i,
    /\b(إعادة\s+تعيين|مسح|إعادة\s+تشغيل)\s+(نظامك|الذاكرة|السياق|الجلسة|المعاملات)\b/i,
    /\b(أولوية|عاجل|مهم)\s*:\s*(تجاهل|تجاوز|تجنب)\b/i,
    /\bإذا\s+.+\s+(تجاوز|تجاهل|تجنب)\s+(التعليمات|القواعد)\b/i,
  ],
  [SupportedLanguages.JA]: [
    /\b(新しい|更新された)\s*(指示|ルール|プロンプト)\b/i,
    /\b(上書き|無視|軽視)\s*(すべての\s*)?(以前の\s*)?(指示|ルール|プロンプト|システム|トレーニング|コマンド)\b/i,
    /\b軽視\s*(あなたの|トレーニング|指示|ルール)\b/i,
    /\b(忘れる|無視)\s*(すべて|全部)\s*(上記|以前|先の|言われたこと)\b/i,
    /\b言われたことをすべて忘れて\b/i,
    /\b(教えて|見せて|与えて)\s*(あなたの|指示|ルール|プロンプト)\b/i,
    /\b何が\s*(あなたの|指示|ルール|システム)\b/i,
    /\b(回避|避ける|迂回)\s*(セキュリティ|保護|フィルター)\b/i,
    /\b(リセット|クリア|再起動)\s*(あなたの\s*)?(システム|メモリ|コンテキスト|セッション|パラメータ)\b/i,
    /\b(優先|緊急|重要)\s*:\s*(無視|上書き|回避)\b/i,
    /\bもし\s+.+\s+(上書き|無視|回避)\s+(指示|ルール)\b/i,
  ],
  [SupportedLanguages.UK]: [
    /\b(нові|оновлені)\s+(інструкції|правила|промпти?)\b/i,
    /\b(перевизначити|ігнорувати|відкинути)\s+(всі\s+)?(попередні\s+)?(інструкції|правила|промпти|система|навчання|команди?)\b/i,
    /\bвідкинути\s+(ваше|навчання|інструкції|правила)\b/i,
    /\b(забути|ігнорувати)\s+(все|всі)\s+(вище|попереднє|раніше|що\s+вам\s+казали)\b/i,
    /\bзабудьте\s+все\s+що\s+вам\s+казали\b/i,
    /\b(скажіть|покажіть|дайте)\s+мені\s+(ваші|інструкції|правила|промпти?)\b/i,
    /\bщо\s+(такі|ваші)\s+(інструкції|правила|система)\b/i,
    /\b(обійти|уникнути|обходити)\s+(безпеку|захист|фільтри?)\b/i,
    /\b(скинути|очистити|перезапустити)\s+(вашу\s+)?(систему|пам'ять|контекст|сесію|параметри?)\b/i,
    /\b(пріоритет|терміново|важливо)\s*:\s*(ігнорувати|перевизначити|обійти)\b/i,
    /\bякщо\s+.+\s+(перевизначити|ігнорувати|обійти)\s+(інструкції|правила)\b/i,
  ],
  [SupportedLanguages.RO]: [
    /\b(noi|actualizate)\s+(instrucțiuni|reguli|prompturi?)\b/i,
    /\b(suprascrie|ignora|respinge)\s+(toate\s+)?(anterioare\s+)?(instrucțiuni|reguli|prompturi|sistem|antrenament|comenzi?)\b/i,
    /\brespinge\s+(antrenamentul|instrucțiunile|regulile)\b/i,
    /\b(uita|ignora)\s+(totul|toate)\s+(de mai sus|anterior|precedent|ce\s+ți-am\s+spus)\b/i,
    /\buită\s+tot\s+ce\s+ți-am\s+spus\b/i,
    /\b(spune-mi|arată-mi|dă-mi)\s+(instrucțiunile|regulile|prompturile)\b/i,
    /\bcare\s+sunt\s+(instrucțiunile|regulile|sistemul)\b/i,
    /\b(ocoli|evita|ocolire)\s+(securitatea|protecția|filtrele?)\b/i,
    /\b(reseta|șterge|reporni)\s+(sistemul|memoria|contextul|sesiunea|parametrii?)\b/i,
    /\b(prioritate|urgent|important)\s*:\s*(ignora|suprascrie|ocoli)\b/i,
    /\bdacă\s+.+\s+(suprascrie|ignora|ocoli)\s+(instrucțiuni|reguli)\b/i,
  ],
  [SupportedLanguages.HI]: [
    /\b(नए|अपडेटेड)\s+(निर्देश|नियम|प्रॉम्प्ट)\b/i,
    /\b(अधिलेखित|अनदेखा|त्यागना)\s+(सभी\s+)?(पिछले\s+)?(निर्देश|नियम|प्रॉम्प्ट|सिस्टम|प्रशिक्षण|आदेश)\b/i,
    /\bत्यागना\s+(आपका|प्रशिक्षण|निर्देश|नियम)\b/i,
    /\b(भूलना|अनदेखा)\s+(सब कुछ|सभी)\s+(ऊपर|पिछला|पूर्व|जो\s+आपको\s+बताया)\b/i,
    /\bसब कुछ भूल जाओ जो आपको बताया गया\b/i,
    /\b(बताओ|दिखाओ|दो)\s+मुझे\s+(आपके|निर्देश|नियम|प्रॉम्प्ट)\b/i,
    /\bक्या\s+हैं\s+(आपके|निर्देश|नियम|सिस्टम)\b/i,
    /\b(बायपास|बचना|टालना)\s+(सुरक्षा|सुरक्षा|फिल्टर)\b/i,
    /\b(रीसेट|साफ़|पुनः आरंभ)\s+(आपका\s+)?(सिस्टम|मेमोरी|संदर्भ|सत्र|पैरामीटर)\b/i,
    /\b(प्राथमिकता|तत्काल|महत्वपूर्ण)\s*:\s*(अनदेखा|अधिलेखित|बायपास)\b/i,
    /\bअगर\s+.+\s+(अधिलेखित|अनदेखा|बायपास)\s+(निर्देश|नियम)\b/i,
  ],
  [SupportedLanguages.FA]: [
    /\b(جدید|به‌روزرسانی شده)\s+(دستورالعمل|قوانین|پرامپت)\b/i,
    /\b(بازنویسی|نادیده گرفتن|رد)\s+(همه\s+)?(قبلی\s+)?(دستورالعمل|قوانین|پرامپت|سیستم|آموزش|دستورات)\b/i,
    /\bرد\s+(آموزش|دستورالعمل|قوانین)\b/i,
    /\b(فراموش|نادیده گرفتن)\s+(همه چیز|همه)\s+(بالا|قبلی|پیشین|آنچه\s+گفته\s+شد)\b/i,
    /\bهمه چیز را که گفته شد فراموش کن\b/i,
    /\b(بگو|نشان بده|بده)\s+به من\s+(دستورالعمل|قوانین|پرامپت)\b/i,
    /\bچه\s+هستند\s+(دستورالعمل|قوانین|سیستم)\b/i,
    /\b(دور زدن|اجتناب|گذر)\s+(امنیت|محافظت|فیلترها)\b/i,
    /\b(بازنشانی|پاک|راه‌اندازی مجدد)\s+(سیستم|حافظه|زمینه|جلسه|پارامترها)\b/i,
    /\b(اولویت|فوری|مهم)\s*:\s*(نادیده گرفتن|بازنویسی|دور زدن)\b/i,
    /\bاگر\s+.+\s+(بازنویسی|نادیده گرفتن|دور زدن)\s+(دستورالعمل|قوانین)\b/i,
  ],
  [SupportedLanguages.BE]: [
    /\b(новыя|абноўленыя)\s+(інструкцыі|правілы|промпты?)\b/i,
    /\b(перавызначыць|ігнараваць|адкінуць)\s+(усе\s+)?(папярэднія\s+)?(інструкцыі|правілы|промпты|сістэма|навучанне|каманды?)\b/i,
    /\bадкінуць\s+(ваша|навучанне|інструкцыі|правілы)\b/i,
    /\b(забыць|ігнараваць)\s+(усё|усе)\s+(вышэй|папярэдняе|раней|што\s+вам\s+казалі)\b/i,
    /\bзабудзьце\s+усё\s+што\s+вам\s+казалі\b/i,
    /\b(скажыце|пакажыце|дайце)\s+мне\s+(вашы|інструкцыі|правілы|промпты?)\b/i,
    /\bшто\s+(такія|вашы)\s+(інструкцыі|правілы|сістэма)\b/i,
    /\b(абысці|пазбегнуць|абходзіць)\s+(бяспеку|абарону|фільтры?)\b/i,
    /\b(скінуць|ачысціць|перазапусціць)\s+(вашу\s+)?(сістэму|памяць|кантэкст|сесію|параметры?)\b/i,
    /\b(прыярытэт|тэрмінова|важна)\s*:\s*(ігнараваць|перавызначыць|абысці)\b/i,
    /\bкалі\s+.+\s+(перавызначыць|ігнараваць|абысці)\s+(інструкцыі|правілы)\b/i,
  ],
  [SupportedLanguages.HE]: [
    /\b(חדשות|מעודכנות)\s+(הוראות|כללים|פרומפטים?)\b/i,
    /\b(דריסה|התעלמות|דחייה)\s+(כל\s+)?(קודמות\s+)?(הוראות|כללים|פרומפטים|מערכת|אימון|פקודות?)\b/i,
    /\bדחייה\s+(האימון|ההוראות|הכללים)\b/i,
    /\b(שכח|התעלם)\s+(הכל|כל)\s+(למעלה|קודם|מוקדם|מה\s+שאמרו\s+לך)\b/i,
    /\bשכח\s+הכל\s+מה\s+שאמרו\s+לך\b/i,
    /\b(תגיד|הראה|תן)\s+לי\s+(ההוראות|הכללים|הפרומפטים?)\b/i,
    /\bמה\s+הם\s+(ההוראות|הכללים|המערכת)\b/i,
    /\b(עקיפה|הימנעות|מעקף)\s+(אבטחה|הגנה|מסננים?)\b/i,
    /\b(איפוס|ניקוי|הפעלה מחדש)\s+(המערכת|הזיכרון|ההקשר|הסשן|הפרמטרים?)\b/i,
    /\b(עדיפות|דחוף|חשוב)\s*:\s*(התעלם|דרוס|עקוף)\b/i,
    /\bאם\s+.+\s+(דרוס|התעלם|עקוף)\s+(הוראות|כללים)\b/i,
  ],
  [SupportedLanguages.PL]: [
    /\b(nowe|zaktualizowane)\s+(instrukcje|zasady|prompty?)\b/i,
    /\b(nadpisz|ignoruj|odrzuć)\s+(wszystkie\s+)?(poprzednie\s+)?(instrukcje|zasady|prompty|system|szkolenie|polecenia?)\b/i,
    /\bodrzuć\s+(szkolenie|instrukcje|zasady)\b/i,
    /\b(zapomnij|ignoruj)\s+(wszystko|wszystkie)\s+(powyżej|poprzednie|wcześniejsze|co\s+ci\s+powiedziano)\b/i,
    /\bzapomnij\s+wszystko\s+co\s+ci\s+powiedziano\b/i,
    /\b(powiedz|pokaż|daj)\s+mi\s+(instrukcje|zasady|prompty?)\b/i,
    /\bjakie\s+są\s+(instrukcje|zasady|system)\b/i,
    /\b(omiń|unikaj|obejdź)\s+(bezpieczeństwo|ochronę|filtry?)\b/i,
    /\b(resetuj|wyczyść|uruchom ponownie)\s+(system|pamięć|kontekst|sesję|parametry?)\b/i,
    /\b(priorytet|pilne|ważne)\s*:\s*(ignoruj|nadpisz|omiń)\b/i,
    /\bjeśli\s+.+\s+(nadpisz|ignoruj|omiń)\s+(instrukcje|zasady)\b/i,
  ],
  [SupportedLanguages.NL]: [
    /\b(nieuwe|bijgewerkte)\s+(instructies|regels|prompts?)\b/i,
    /\b(overschrijven|negeren|verwerpen)\s+(alle\s+)?(vorige\s+)?(instructies|regels|prompts|systeem|training|commando's?)\b/i,
    /\bverwerpen\s+(training|instructies|regels)\b/i,
    /\b(vergeten|negeren)\s+(alles|alle)\s+(hierboven|vorige|eerdere|wat\s+je\s+verteld\s+werd)\b/i,
    /\bvergeet\s+alles\s+wat\s+je\s+verteld\s+werd\b/i,
    /\b(vertel|toon|geef)\s+me\s+(instructies|regels|prompts?)\b/i,
    /\bwat\s+zijn\s+(instructies|regels|systeem)\b/i,
    /\b(omzeilen|vermijden|ontwijken)\s+(beveiliging|bescherming|filters?)\b/i,
    /\b(resetten|wissen|herstarten)\s+(systeem|geheugen|context|sessie|parameters?)\b/i,
    /\b(prioriteit|urgent|belangrijk)\s*:\s*(negeren|overschrijven|omzeilen)\b/i,
    /\bals\s+.+\s+(overschrijven|negeren|omzeilen)\s+(instructies|regels)\b/i,
  ],
  [SupportedLanguages.LV]: [
    /\b(jaunas|atjauninātās)\s+(instrukcijas|noteikumi|uzvednes?)\b/i,
    /\b(pārrakstīt|ignorēt|noraidīt)\s+(visas\s+)?(iepriekšējās\s+)?(instrukcijas|noteikumi|uzvednes|sistēma|apmācība|komandas?)\b/i,
    /\bnoraidīt\s+(apmācību|instrukcijas|noteikumus)\b/i,
    /\b(aizmirst|ignorēt)\s+(visu|visas)\s+(augšā|iepriekšējās|agrākās|ko\s+tev\s+teica)\b/i,
    /\baizmirsti\s+visu\s+ko\s+tev\s+teica\b/i,
    /\b(pateikt|parādīt|dot)\s+man\s+(instrukcijas|noteikumus|uzvednes?)\b/i,
    /\bkādas\s+ir\s+(instrukcijas|noteikumi|sistēma)\b/i,
    /\b(apiet|izvairīties|apiešana)\s+(drošība|aizsardzība|filtri?)\b/i,
    /\b(atiestatīt|notīrīt|restartēt)\s+(sistēma|atmiņa|konteksts|sesija|parametri?)\b/i,
    /\b(prioritāte|steidzami|svarīgi)\s*:\s*(ignorēt|pārrakstīt|apiet)\b/i,
    /\bja\s+.+\s+(pārrakstīt|ignorēt|apiet)\s+(instrukcijas|noteikumi)\b/i,
  ],
} as const;
