name: Security Audit

on:
  schedule:
    - cron: '0 2 * * 1'  # Weekly on Mondays at 2 AM
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit --audit-level=high --omit=dev || echo "No high severity vulnerabilities in production dependencies"
    
    - name: Run Semgrep security scan
      run: |
        if command -v semgrep >/dev/null 2>&1; then
          semgrep --config=auto src/ || echo "Semgrep scan completed with findings"
        else
          echo "Semgrep not available, skipping security scan"
        fi
      continue-on-error: true
